language: php
php:
- '5.4'
- '5.5'
- '5.6'
- '7'
matrix:
  allow_failures:
  - php: 7
before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-source --dev
script:
- ./shell/ci-phpunit-code-coverage.sh
after_script:
- php bin/ocular code-coverage:upload --format=php-clover build/coverage.clover
